title: DineStar
description: Sustainable Palm Leaf Dinnerware - Nature's Craft for Your Table.
url: https://ajithsinghsajitha.github.io
baseurl: /dinestar

exclude:
  - README.md
  - .claude
  - .env*
  - Gemfile
  - Gemfile.lock
  - vendor
  - cms-auth
