items:
  - name: Artisan Square Plate
    description: Perfect for main courses and elegant presentations.
    price: $99.99 / pack
    image: /assets/images/uploads/whatsapp-image-2026-04-20-at-9.25.07-am.jpeg
  - name: Deep Salad Bowl AAA
    description: Ideal for salads, soups, and shared appetizers.
    price: $19.99 / pack
    image: https://picsum.photos/seed/bowl1/600/600
  - name: Wooden Cutlery Set
    description: Biodegradable birch wood forks, knives, and spoons.
    price: $12.99 / pack
    image: https://picsum.photos/seed/cutlery1/600/600
  - name: Plates 10'
    description: |-
      round 
      brown
    price: $12.99
    image: /assets/images/uploads/ds-logo-2.png
