items:
  - name: "6'' "
    description: Round Deep plate
    price: Rs. 5 / pc
    image: /assets/images/uploads/6-round-deep-plate.png
  - name: 4''
    description: Square Deep Bowl
    price: Rs 3 / pc
    image: /assets/images/uploads/4-square-deep-bowl.png
  - name: 8''
    description: "Deep Round Plate "
    price: Rs 3 / pc
    image: /assets/images/uploads/8-deep-round-plate.png
  - name: 12''
    description: Deep round Plate
    price: Rs 3/pc
    image: /assets/images/uploads/12-deep-round-plate.png
  - name: 6''
    description: "Square Plate "
    price: Rs 3/pc
    image: /assets/images/uploads/6-sqaure-plate.png
  - name: 9''
    description: "3C Square Deep Plate "
    price: Rs 3/pc
    image: /assets/images/uploads/9-square-3c-deep-plate.png
  - name: "9'' x 6'' "
    description: Rectangular Tray
    price: "Rs 3/pc "
    image: /assets/images/uploads/9-x-6-rectangular-tray.png
